/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uca.proyecto_poo;


/**
 *
 * @author HP
 */
public class Pokemon extends javax.swing.JFrame {

    /**
     * Creates new form Pokemon
     */
    public Pokemon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblEevee = new javax.swing.JLabel();
        btnEevee = new javax.swing.JButton();
        lblNormal = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblVaporeon = new javax.swing.JLabel();
        btnVaporeon = new javax.swing.JButton();
        lblAgua = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblFlareon = new javax.swing.JLabel();
        btnFlareon = new javax.swing.JButton();
        lblFuego = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblJolteon = new javax.swing.JLabel();
        btnJolteon = new javax.swing.JButton();
        lblElectrico = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblEspeon = new javax.swing.JLabel();
        btnEspeon = new javax.swing.JButton();
        lblPsiquico = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lblLeafeon = new javax.swing.JLabel();
        btnLeafeon = new javax.swing.JButton();
        lblPlanta = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lblGlaceon = new javax.swing.JLabel();
        btnGlaceon = new javax.swing.JButton();
        lblHielo = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lblUmbreon = new javax.swing.JLabel();
        btnUmbreon = new javax.swing.JButton();
        lblSiniestro = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        lblSylveon = new javax.swing.JLabel();
        btnSylveon = new javax.swing.JButton();
        lblHada = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblTitulo.setText("Eevee y sus evoluciones:");

        lblEevee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uca/proyecto_poo/resources/Eevee.png"))); // NOI18N

        btnEevee.setText("Eevee");
        btnEevee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEeveeActionPerformed(evt);
            }
        });

        lblNormal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNormal.setText("Tipo Normal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNormal)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblEevee)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEevee)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNormal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEevee)
                    .addComponent(btnEevee))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblVaporeon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uca/proyecto_poo/resources/Vaporeon.png"))); // NOI18N

        btnVaporeon.setText("Vaporeon");
        btnVaporeon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaporeonActionPerformed(evt);
            }
        });

        lblAgua.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAgua.setText("Tipo Agua");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAgua)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblVaporeon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVaporeon))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAgua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVaporeon)
                    .addComponent(btnVaporeon))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblFlareon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uca/proyecto_poo/resources/Flareon.png"))); // NOI18N

        btnFlareon.setText("Flareon");
        btnFlareon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFlareonActionPerformed(evt);
            }
        });

        lblFuego.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFuego.setText("Tipo Fuego");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblFlareon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFlareon))
                    .addComponent(lblFuego))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFuego)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFlareon)
                    .addComponent(btnFlareon))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblJolteon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uca/proyecto_poo/resources/Jolteon.png"))); // NOI18N

        btnJolteon.setText("Jolteon");
        btnJolteon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJolteonActionPerformed(evt);
            }
        });

        lblElectrico.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblElectrico.setText("Tipo Electrico");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblElectrico)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblJolteon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnJolteon)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblElectrico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJolteon)
                    .addComponent(btnJolteon))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblEspeon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uca/proyecto_poo/resources/Espeon.png"))); // NOI18N

        btnEspeon.setText("Espeon");
        btnEspeon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEspeonActionPerformed(evt);
            }
        });

        lblPsiquico.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPsiquico.setText("Tipo Psiquico");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblEspeon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEspeon))
                    .addComponent(lblPsiquico))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPsiquico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEspeon)
                    .addComponent(btnEspeon))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        lblLeafeon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uca/proyecto_poo/resources/Leafeon.png"))); // NOI18N

        btnLeafeon.setText("Leafeon");
        btnLeafeon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeafeonActionPerformed(evt);
            }
        });

        lblPlanta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPlanta.setText("Tipo Planta");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPlanta)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lblLeafeon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLeafeon)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPlanta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLeafeon)
                    .addComponent(btnLeafeon))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblGlaceon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uca/proyecto_poo/resources/Glaceon.png"))); // NOI18N

        btnGlaceon.setText("Glaceon");
        btnGlaceon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGlaceonActionPerformed(evt);
            }
        });

        lblHielo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblHielo.setText("Tipo Hielo");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHielo)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(lblGlaceon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGlaceon)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHielo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGlaceon)
                    .addComponent(btnGlaceon))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblUmbreon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uca/proyecto_poo/resources/Umbreon.png"))); // NOI18N

        btnUmbreon.setText("Umbreon");
        btnUmbreon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUmbreonActionPerformed(evt);
            }
        });

        lblSiniestro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSiniestro.setText("Tipo Siniestro");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSiniestro)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(lblUmbreon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUmbreon)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSiniestro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUmbreon)
                    .addComponent(btnUmbreon))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblSylveon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uca/proyecto_poo/resources/Sylveon.png"))); // NOI18N

        btnSylveon.setText("Sylveon");
        btnSylveon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSylveonActionPerformed(evt);
            }
        });

        lblHada.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblHada.setText("Tipo Hada");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHada)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(lblSylveon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSylveon)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSylveon)
                    .addComponent(btnSylveon))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 84, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEeveeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEeveeActionPerformed
        String audioFilePath = "src/main/java/uca/proyecto_poo/resources/Grito_de_Eevee.wav";
        EjemploClip sonidoEevee = new EjemploClip();
        sonidoEevee.play(audioFilePath);
    }//GEN-LAST:event_btnEeveeActionPerformed

    private void btnSylveonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSylveonActionPerformed
        String audioFilePath = "src/main/java/uca/proyecto_poo/resources/Grito_de_Sylveon.wav";
        EjemploClip sonidoSylveon = new EjemploClip();
        sonidoSylveon.play(audioFilePath);
    }//GEN-LAST:event_btnSylveonActionPerformed

    private void btnFlareonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFlareonActionPerformed
        String audioFilePath = "src/main/java/uca/proyecto_poo/resources/Grito_de_Flareon.wav";
        EjemploClip sonidoFlareon = new EjemploClip();
        sonidoFlareon.play(audioFilePath);
    }//GEN-LAST:event_btnFlareonActionPerformed

    private void btnLeafeonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeafeonActionPerformed
        String audioFilePath = "src/main/java/uca/proyecto_poo/resources/Grito_de_Leafeon.wav";
        EjemploClip sonidoLeafeon = new EjemploClip();
        sonidoLeafeon.play(audioFilePath);
    }//GEN-LAST:event_btnLeafeonActionPerformed

    private void btnJolteonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJolteonActionPerformed
        String audioFilePath = "src/main/java/uca/proyecto_poo/resources/Grito_de_Jolteon.wav";
        EjemploClip sonidoJolteon = new EjemploClip();
        sonidoJolteon.play(audioFilePath);
    }//GEN-LAST:event_btnJolteonActionPerformed

    private void btnEspeonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEspeonActionPerformed
        String audioFilePath = "src/main/java/uca/proyecto_poo/resources/Grito_de_Espeon.wav";
        EjemploClip sonidoEspeon = new EjemploClip();
        sonidoEspeon.play(audioFilePath);
    }//GEN-LAST:event_btnEspeonActionPerformed

    private void btnVaporeonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaporeonActionPerformed
        String audioFilePath = "src/main/java/uca/proyecto_poo/resources/Grito_de_Vaporeon.wav";
        EjemploClip sonidoVaporeon = new EjemploClip();
        sonidoVaporeon.play(audioFilePath);
    }//GEN-LAST:event_btnVaporeonActionPerformed

    private void btnGlaceonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGlaceonActionPerformed
        String audioFilePath = "src/main/java/uca/proyecto_poo/resources/Grito_de_Glaceon.wav";
        EjemploClip sonidoGlaceon = new EjemploClip();
        sonidoGlaceon.play(audioFilePath);
    }//GEN-LAST:event_btnGlaceonActionPerformed

    private void btnUmbreonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUmbreonActionPerformed
        String audioFilePath = "src/main/java/uca/proyecto_poo/resources/Grito_de_Umbreon.wav";
        EjemploClip sonidoUmbreon = new EjemploClip();
        sonidoUmbreon.play(audioFilePath);
    }//GEN-LAST:event_btnUmbreonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pokemon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEevee;
    private javax.swing.JButton btnEspeon;
    private javax.swing.JButton btnFlareon;
    private javax.swing.JButton btnGlaceon;
    private javax.swing.JButton btnJolteon;
    private javax.swing.JButton btnLeafeon;
    private javax.swing.JButton btnSylveon;
    private javax.swing.JButton btnUmbreon;
    private javax.swing.JButton btnVaporeon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblAgua;
    private javax.swing.JLabel lblEevee;
    private javax.swing.JLabel lblElectrico;
    private javax.swing.JLabel lblEspeon;
    private javax.swing.JLabel lblFlareon;
    private javax.swing.JLabel lblFuego;
    private javax.swing.JLabel lblGlaceon;
    private javax.swing.JLabel lblHada;
    private javax.swing.JLabel lblHielo;
    private javax.swing.JLabel lblJolteon;
    private javax.swing.JLabel lblLeafeon;
    private javax.swing.JLabel lblNormal;
    private javax.swing.JLabel lblPlanta;
    private javax.swing.JLabel lblPsiquico;
    private javax.swing.JLabel lblSiniestro;
    private javax.swing.JLabel lblSylveon;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUmbreon;
    private javax.swing.JLabel lblVaporeon;
    // End of variables declaration//GEN-END:variables
}
